
C FTANGLE v1.61,
C created with UNIX on "Friday, September 25, 1998 at 8:02." 
C  COMMAND LINE: "ftangle -ybs15000 traceb"
C  RUN TIME:     "Friday, June 5, 2009 at 15:05."
C  WEB FILE:     "traceb.web"
C  CHANGE FILE:  (none)
      C* 1: * 
*line 14 "traceb.web"
      subroutine traceb
      implicit none
      real w
      
      write(6,99001)
      
99001 format(' This TRACEBACK is generated by SQRT(-1.0)')
      
      w=-1
      w=sqrt(w)
      write(6,*)w
      return
      
      end
C* :1 * 
      
